#---------------------
# Github Action Basics
name: My-GithubActions-Basics

on: 
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in testing
      run: echo "Hello World from testing job"




  deploying:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
    - name: Print Hello Message in deploy
      run: echo "Hello World from deploy job"
